apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: color-app
  namespace: argocd
spec:
  destination:
    namespace: jumping
    server: https://kubernetes.default.svc
  source:
    path: .   # Update this to match the directory in your repo where Kubernetes manifests will be stored
    repoURL: https://github.com/devopsclinics/jumping-cat.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
